import React, { useState } from 'react';
import { X, Copy, Check, Download, FileText, Code2 } from 'lucide-react';
import { ProjectAnalysisResult } from '../../engine/types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: ProjectAnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, data }) => {
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    return `# Red Bull Racing Architecture Telemetry: ${data.projectName}
Generated by **ProjectLens** on ${new Date(data.timestamp).toLocaleString()}

## 1. Aerodynamic Architecture Overview
- **Pattern:** ${data.architecture.pattern} (${data.architecture.confidence}% Confidence)
- **Primary Framework:** ${data.primaryFramework}
- **Runtime:** ${data.primaryRuntime}
- **Styling Engine:** ${data.stylingEngine}
- **State Management:** ${data.stateLayer}
- **AI Stack:** ${data.aiLayer}
- **AI Readiness RPM Score:** ${data.aiConfig.readinessScore}/100

### Architectural Summary
${data.architecture.summary}

### Data Flow Circuit
\`${data.architecture.dataFlowSummary}\`

## 2. Power Unit & Stack Breakdown (${data.dependencies.length} Components)
| Component | Category | Level | Purpose | Architectural Significance |
|---|---|---|---|---|
${data.dependencies
  .map(
    (d) =>
      `| **${d.name}** | \`${d.category}\` | ${d.level.toUpperCase()} | ${d.purpose.replace(/\|/g, '-')} | ${d.significance.replace(/\|/g, '-')} |`
  )
  .join('\n')}

## 3. Pit Wall AI Workspace Configuration
- Cursor Rules (.cursorrules): ${data.aiConfig.hasCursorRules ? 'Active' : 'Missing'}
- Claude / Agent Directives (CLAUDE.md): ${data.aiConfig.hasClaudeInstructions ? 'Active' : 'Missing'}
- MCP Telemetry Servers: ${data.aiConfig.mcpServers.length} configured
- Environment Variables Required: ${data.aiConfig.environmentKeys.join(', ') || 'None'}

### Pit Wall Directives & Tuning
${data.aiConfig.recommendations.map((r) => `- ${r}`).join('\n') || '- None: fully tuned for maximum lap pace!'}

---
*Generated by ProjectLens Red Bull Racing Telemetry - Antigravity & VS Code Webview*
`;
  };

  const content = format === 'markdown' ? generateMarkdown() : JSON.stringify(data, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `${data.projectName.toLowerCase().replace(/\s+/g, '-')}-telemetry.${
      format === 'markdown' ? 'md' : 'json'
    }`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/75 backdrop-blur-md z-50 flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-[#091c38] border border-white/10 rounded-2xl w-full max-w-3xl shadow-2xl flex flex-col max-h-[85vh] overflow-hidden relative">
        {/* Top Racing Stripe */}
        <div className="h-1 w-full bg-gradient-to-r from-[#e00034] via-[#ffd100] to-transparent" />

        {/* Header */}
        <div className="flex items-center justify-between p-5 px-6 border-b border-white/10 bg-[#051329]">
          <div className="flex items-center gap-3.5">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-[#e00034] to-[#ffd100] text-white flex items-center justify-center shadow-rb-red">
              <Download className="w-5 h-5 text-white" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-black text-base text-white tracking-tight uppercase font-sans italic">
                  EXPORT TELEMETRY REPORT
                </h3>
                <span className="rb-racing-badge text-[10px] font-mono px-2 py-0.5 rounded bg-[#e00034] text-white font-black">
                  <span>TELEMETRY</span>
                </span>
              </div>
              <p className="text-[11px] text-slate-400 font-medium">Download architecture specs for team reviews, PRs, and pit lane debriefs</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-white hover:bg-white/10 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="flex items-center justify-between px-6 py-3 bg-[#07172e] border-b border-white/10 text-xs">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-mono text-xs font-bold ${
                format === 'markdown'
                  ? 'bg-[#e00034] text-white shadow-rb-red'
                  : 'text-slate-300 hover:text-white bg-[#0e2447] border border-white/10'
              }`}
            >
              <FileText className="w-3.5 h-3.5 text-[#ffd100]" />
              Markdown (.md)
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-mono text-xs font-bold ${
                format === 'json'
                  ? 'bg-[#e00034] text-white shadow-rb-red'
                  : 'text-slate-300 hover:text-white bg-[#0e2447] border border-white/10'
              }`}
            >
              <Code2 className="w-3.5 h-3.5 text-[#ffd100]" />
              JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs bg-[#0e2447] hover:bg-[#162f59] text-white px-3 py-1.5 rounded-xl border border-white/10 transition font-bold"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-[#ffd100]" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs bg-gradient-to-r from-[#e00034] to-[#ff003c] hover:from-[#c2002d] hover:to-[#e00034] text-white px-4 py-1.5 rounded-xl font-bold transition shadow-rb-red"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-slate-200 bg-[#030b17]">
          <pre className="whitespace-pre-wrap leading-relaxed">{content}</pre>
        </div>
      </div>
    </div>
  );
};
