import React, { useState } from 'react';
import { X, Copy, Check, Download, FileText, Code2 } from 'lucide-react';
import { ProjectAnalysisResult } from '../../engine/types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: ProjectAnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, data }) => {
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    return `# Architecture Report: ${data.projectName}
Generated by **ProjectLens** on ${new Date(data.timestamp).toLocaleString()}

## 1. Architecture Overview
- **Pattern:** ${data.architecture.pattern} (${data.architecture.confidence}% Confidence)
- **Primary Framework:** ${data.primaryFramework}
- **Runtime:** ${data.primaryRuntime}
- **Styling Engine:** ${data.stylingEngine}
- **State Management:** ${data.stateLayer}
- **AI Stack:** ${data.aiLayer}
- **AI Readiness Score:** ${data.aiConfig.readinessScore}/100

### Architectural Summary
${data.architecture.summary}

### Data Flow
\`${data.architecture.dataFlowSummary}\`

## 2. Technology Stack Breakdown (${data.dependencies.length} Libraries)
| Package | Category | Level | Purpose | Architectural Significance |
|---|---|---|---|---|
${data.dependencies
  .map(
    (d) =>
      `| **${d.name}** | \`${d.category}\` | ${d.level.toUpperCase()} | ${d.purpose.replace(/\|/g, '-')} | ${d.significance.replace(/\|/g, '-')} |`
  )
  .join('\n')}

## 3. AI Workspace Configuration
- Cursor Rules (.cursorrules): ${data.aiConfig.hasCursorRules ? 'Active' : 'Missing'}
- Claude / Agent Directives (CLAUDE.md): ${data.aiConfig.hasClaudeInstructions ? 'Active' : 'Missing'}
- MCP Tool Servers: ${data.aiConfig.mcpServers.length} configured
- Environment Variables Required: ${data.aiConfig.environmentKeys.join(', ') || 'None'}

### Agent Alignment Recommendations
${data.aiConfig.recommendations.map((r) => `- ${r}`).join('\n') || '- None: fully aligned!'}

---
*Generated by ProjectLens - Embedded Workspace Inspector for Antigravity & VS Code*
`;
  };

  const content = format === 'markdown' ? generateMarkdown() : JSON.stringify(data, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `${data.projectName.toLowerCase().replace(/\s+/g, '-')}-architecture.${
      format === 'markdown' ? 'md' : 'json'
    }`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4">
      <div className="bg-[#0b1220] border border-white/[0.1] rounded-2xl w-full max-w-3xl shadow-2xl flex flex-col max-h-[85vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-4 px-6 border-b border-white/[0.08] bg-[#070b16]">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-sky-500/20 border border-sky-500/30 flex items-center justify-center">
              <Download className="w-4 h-4 text-sky-400" />
            </div>
            <div>
              <h3 className="font-bold text-sm text-white">Export Architecture Report</h3>
              <p className="text-[11px] text-slate-400">Export for documentation, team PRs, or architecture reviews</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-white/[0.08] transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="flex items-center justify-between px-6 py-3 bg-[#0d1424]/60 border-b border-white/[0.06] text-xs">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-medium ${
                format === 'markdown'
                  ? 'bg-sky-500 text-white shadow-sm'
                  : 'text-slate-400 hover:text-white bg-white/[0.04]'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              Markdown (.md)
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-medium ${
                format === 'json'
                  ? 'bg-sky-500 text-white shadow-sm'
                  : 'text-slate-400 hover:text-white bg-white/[0.04]'
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs bg-white/[0.06] hover:bg-white/[0.1] text-slate-200 px-3 py-1.5 rounded-lg border border-white/[0.08] transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs bg-sky-500 hover:bg-sky-600 text-white px-3.5 py-1.5 rounded-lg font-semibold transition shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-slate-300 bg-[#060913]">
          <pre className="whitespace-pre-wrap leading-relaxed">{content}</pre>
        </div>
      </div>
    </div>
  );
};
