import React, { useState } from 'react';
import { X, Copy, Check, Download, FileText, Code2 } from 'lucide-react';
import { ProjectAnalysisResult } from '../../engine/types';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  data: ProjectAnalysisResult;
}

export const ExportModal: React.FC<ExportModalProps> = ({ isOpen, onClose, data }) => {
  const [format, setFormat] = useState<'markdown' | 'json'>('markdown');
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    return `# Architecture Report: ${data.projectName}
Generated by **ProjectLens** on ${new Date(data.timestamp).toLocaleString()}

## 1. Architecture Overview
- **Pattern:** ${data.architecture.pattern} (${data.architecture.confidence}% Confidence)
- **Primary Framework:** ${data.primaryFramework}
- **Runtime:** ${data.primaryRuntime}
- **Styling Engine:** ${data.stylingEngine}
- **State Management:** ${data.stateLayer}
- **AI Stack:** ${data.aiLayer}
- **AI Readiness Score:** ${data.aiConfig.readinessScore}/100

### Architectural Summary
${data.architecture.summary}

### Data Flow
\`${data.architecture.dataFlowSummary}\`

## 2. Technology Stack Breakdown (${data.dependencies.length} Libraries)
| Package | Category | Level | Purpose | Architectural Significance |
|---|---|---|---|---|
${data.dependencies
  .map(
    (d) =>
      `| **${d.name}** | \`${d.category}\` | ${d.level.toUpperCase()} | ${d.purpose.replace(/\|/g, '-')} | ${d.significance.replace(/\|/g, '-')} |`
  )
  .join('\n')}

## 3. AI Workspace Configuration
- Cursor Rules (.cursorrules): ${data.aiConfig.hasCursorRules ? 'Active' : 'Missing'}
- Claude / Agent Directives (CLAUDE.md): ${data.aiConfig.hasClaudeInstructions ? 'Active' : 'Missing'}
- MCP Tool Servers: ${data.aiConfig.mcpServers.length} configured
- Environment Variables Required: ${data.aiConfig.environmentKeys.join(', ') || 'None'}

### Agent Alignment Recommendations
${data.aiConfig.recommendations.map((r) => `- ${r}`).join('\n') || '- None: fully aligned!'}

---
*Generated by ProjectLens - Embedded Workspace Inspector for Antigravity & VS Code*
`;
  };

  const content = format === 'markdown' ? generateMarkdown() : JSON.stringify(data, null, 2);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const filename = `${data.projectName.toLowerCase().replace(/\s+/g, '-')}-architecture.${
      format === 'markdown' ? 'md' : 'json'
    }`;
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 bg-slate-900/50 backdrop-blur-sm z-50 flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200 rounded-3xl w-full max-w-3xl shadow-2xl flex flex-col max-h-[85vh] overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between p-5 px-6 border-b border-slate-100 bg-slate-50/70">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-2xl bg-blue-100 text-blue-700 flex items-center justify-center shadow-sm">
              <Download className="w-5 h-5 text-blue-600" />
            </div>
            <div>
              <h3 className="font-bold text-sm text-slate-900">Export Architecture Report</h3>
              <p className="text-[11px] text-slate-500">Export for documentation, team PRs, or architecture reviews</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Format Selector Bar */}
        <div className="flex items-center justify-between px-6 py-3 bg-white border-b border-slate-100 text-xs">
          <div className="flex items-center gap-2">
            <button
              onClick={() => setFormat('markdown')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-medium ${
                format === 'markdown'
                  ? 'bg-blue-600 text-white shadow-sm font-bold'
                  : 'text-slate-600 hover:text-slate-900 bg-slate-100'
              }`}
            >
              <FileText className="w-3.5 h-3.5" />
              Markdown (.md)
            </button>
            <button
              onClick={() => setFormat('json')}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg transition font-medium ${
                format === 'json'
                  ? 'bg-blue-600 text-white shadow-sm font-bold'
                  : 'text-slate-600 hover:text-slate-900 bg-slate-100'
              }`}
            >
              <Code2 className="w-3.5 h-3.5" />
              JSON (.json)
            </button>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 text-xs bg-slate-100 hover:bg-slate-200 text-slate-700 px-3 py-1.5 rounded-xl border border-slate-200 transition font-medium"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-1.5 text-xs bg-blue-600 hover:bg-blue-700 text-white px-3.5 py-1.5 rounded-xl font-semibold transition shadow-sm"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download File</span>
            </button>
          </div>
        </div>

        {/* Content Preview */}
        <div className="p-5 overflow-y-auto flex-1 font-mono text-xs text-slate-100 bg-slate-900">
          <pre className="whitespace-pre-wrap leading-relaxed">{content}</pre>
        </div>
      </div>
    </div>
  );
};
